### ISSUE TITLE
1.19.3 support?

### ISSUE THREAD

**Issue by EL-S** [michiruf/MCServerPortals#1]
I saw your reddit post about how there doesn't seem to be a velocity plugin that lets you use portals to travel between servers. Unfortunately for my use case I'm stuck with 1.19.3 due to geyser+switch support.

Thanks in advance!

**Comment by michiruf** [comment]
I looked into upgrading today, without losing the possibility to maintain 1.19.2 aswell, and couldn't figure this out yet.
Ill let you know when I make any progress or if I can manage to do so, but im on it!
