### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wicivo** [michiruf/MCServerPortals#6]
https://mclo.gs/CX9562Z

**Comment by michiruf** [comment]
You need to specify a specific version for fabric API in order for the plugin to work. This is not on me, but on https://github.com/kyrptonaught/customportalapi . 
The version you need i specified here: https://github.com/michiruf/MCServerPortals/blob/2b8923c6a000f7e7e789619dcc7ea6719df4478d/build.versions.gradle#L65

**Comment by michiruf** [comment]
If that still does not work, let me know

**Comment by wicivo** [comment]
> If that still does not work, let me know

It's working, but now the chat stops working

**Comment by michiruf** [comment]
I dont know why this would happen, has this anything to do with downgrading fabric?

**Comment by wicivo** [comment]
idk

**Comment by wicivo** [comment]
Do you have a discord?

**Comment by wicivo** [comment]
It's more convenient to communicate that way, and I also found the problem.

**Comment by michiruf** [comment]
I prefer this way
